### ISSUE TITLE
How to implement automatic capture with this plugin?

### ISSUE THREAD

**Issue by MDSADABWASIM** [gibbsvjy007/flutter_razorpay_sdk#3]
As of now we have to use Order API to get automatic capture feature https://docs.razorpay.com/page/orders but I dont know how to start working with this flutter plugin.

**Comment by vijayawoshe** [comment]
Hello Wasim,

Thanks for informing.

Can you please clone this project and add this feature if you have time. You can create pull-request. If you don't have time atm then I will add it once I will get some time. We will also need this feature in one of our projects.

Thanks.

Regards
Vijay

**Comment by MDSADABWASIM** [comment]
Thanks for asking Vijay, but I don't have time either, I'm currently working on a project and I've been very busy in that.

It'll be real pleasure for me and flutter community if you solve this issue.

**Comment by raveesh-me** [comment]
Hi!
Chiming in without invitation :lollipop: 
Fire orders API from your backend, get the order details, pass it to the checkout function and you are done!
You will get the secrets when checkout ends, upload it to your backend and check if payment was successful using their hmac algo and move towards fulfillment

**Comment by raveesh-me** [comment]
There is an officially maintained razorpay plugin!

https://github.com/razorpay/razorpay-android-sample-app/issues/96
